### ISSUE TITLE
Typescript to JSON Schema does not seem to be working.

### ISSUE THREAD

**Issue by azizhk** [ritz078/transform#182]
https://transform.tools/typescript-to-json-schema
API is throwing 500 with response:
```
Cannot find global type 'Array'.

Cannot find global type 'Boolean'.

Cannot find global type 'Function'.

Cannot find global type 'IArguments'.

Cannot find global type 'Number'.

Cannot find global type 'Object'.

Cannot find global type 'RegExp'.

Cannot find global type 'String'.

File '/var/task/node_modules/ts-json-schema-generator/node_modules/typescript/lib/lib.d.ts' not found.
```

<img width="1630" alt="Screenshot 2020-06-04 at 11 34 11 AM" src="https://user-images.githubusercontent.com/5094296/83720827-801d7080-a657-11ea-83aa-9111fd39b132.png">

**Comment by ritz078** [comment]
It looks like this works locally but fails in production.

Since vercel converts api to lambdas, I am not able to create temporary files in production.

https://github.com/ritz078/transform/blob/618bd8d5bcbe7e308ee0ec6aa7be0396db2aa3a7/pages/api/typescript-to-json-schema.ts#L8

Do you have workaround for this in mind?

**Comment by azizhk** [comment]
I think next creates individual bundles for each api route.
And that merges only the js files, not the ts files.

**Comment by ritz078** [comment]
Yes. every api route is a different lambda.
